spring:
  application:
    name: "core"
  devtools:
    add-properties: false
  profiles:
    include:
      - jpaadapter
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /core

actuator:
  auth-token-header-name: ${ACTUATOR_API_KEY_NAME:API-KEY}
  auth-token: ${ACTUATOR_AUTH_TOKEN:TOKEN}